### ISSUE TITLE
Add download history button

### ISSUE THREAD

**Issue by poludnev** [chainhackers/gamejutsu-demos#100]
Add a button that downloads game history by gameId.

History should be downloaded as a txt file with data in YAML format.

@ghUserrrr please try to implement the features below: 

- [x] setup a YAML lib to stringify the history array
- [x] filter the history array to remove unused or redundant info
- [x] download a txt file with filters info

**Comment by originalskobka** [comment]
Без совершения ходов файл, не качается.
После совершения ходов, файл качается. 
После совершения чит-хода, файл качается.
После завершения игры победой, файл качается.
После завершения игры дисквалификацией, файл качается.
