### ISSUE TITLE
В мобильной версии кнопка "Checkers rules notice"  не имеет границы  и отсутствует текст в кнопке

### ISSUE THREAD

**Issue by originalskobka** [chainhackers/gamejutsu-demos#113]
**Предусловия**:

1. Подключиться к сайту с двух аккаунтов.

2. С первого аккаунта создать игру в Checkers

3. Со второго аккаунта на мобильном устройстве подключиться к игре через кнопку JOIN

4. Апрувнуть все.

**Шаги воспроизведения**:

1. Посмотреть на кнопку "Checkers rules notice"

**Ожидаемый результат**:

1. Кнопка имеет границы

2. У кнопки есть текст "Checkers rules notice"

**Фактический результат**:

1. Кнопка не имеет границ по правой стороне

2. Отсутствует текст на кнопке "Checkers rules notice"

![Image](https://user-images.githubusercontent.com/121563260/213370938-5ee7355f-bcc9-4379-bcd4-6fa7993aa7a3.png)

**Comment by ghUserrrr** [comment]
fixed
![Image](https://user-images.githubusercontent.com/109285732/213906134-9fd90ba5-b804-49b0-b698-7c897d1d7356.png)

**Comment by originalskobka** [comment]
Кнопка отображается корректно 

![Image](https://user-images.githubusercontent.com/121563260/213922010-aa70aea5-736e-4a05-83e2-b09394d1762c.png)
