### ISSUE TITLE
В web-версии кнопка "Checkers rules notice" при изменении разрешения браузера сдвигается в правую сторону

### ISSUE THREAD

**Issue by originalskobka** [chainhackers/gamejutsu-demos#114]
**Предусловия**:

1. Подключиться к сайту с двух аккаунтов.

2. С первого аккаунта создать игру в Checkers.

3. Со второго аккаунта подключиться к игре через кнопку JOIN.

4. Апрувнуть все.

**Шаги воспроизведения**:

1. Уменьшаем разрешение браузера до 991х1190 (второе значение может быть любым, оно нас не волнует, обращаем внимание на первое значение - ширину).
2. Смотрим на кнопку.
3. Продолжаем уменьшать разрешение браузера в ширину.

**Ожидаемый результат**:

1. Кнопка адаптируется под изменение разрешение браузера.  Все элементы в кнопке адаптируются под изменение разрешения браузера.

**Фактический результат**:

1. На брейкпоинте 991х1190 появляется кнопка. Кружок с восклицательным знаком находится за пределами кнопки. 

![Image](https://user-images.githubusercontent.com/121563260/213375020-eff893a3-3598-4336-ae5f-3ee9750fc920.JPG)

2. При дальнейшем уменьшении разрешения кнопка начинает двигаться, с брейкпоинта 948х1190 кнопка начинает выходить за рамки 

![Image](https://user-images.githubusercontent.com/121563260/213375363-ae64999e-232f-4f9f-b022-98f8d852a565.JPG)

3.  Если продолжить уменьшать разрешение браузера, то кнопка продолжает смещаться. Текст кнопки становится недоступным. Кликнуть на кнопку нет возможности

Видео - https://disk.yandex.ru/i/P_3RiIOflHqWXA

**Comment by ghUserrrr** [comment]
fixed
![Image](https://user-images.githubusercontent.com/109285732/213906483-69547e44-e8d3-4bd4-9e51-10d4f043fa8a.png)

**Comment by originalskobka** [comment]
Кнопка адаптируется под изменение разрешения браузера.

![Image](https://user-images.githubusercontent.com/121563260/213921995-05637bfb-5f8b-4557-984a-a47dfb5cb800.JPG)
