### ISSUE TITLE
Кнопка "Checkers rules notice" кликается исключительно при нажатии по тексту

### ISSUE THREAD

**Issue by originalskobka** [chainhackers/gamejutsu-demos#118]
**Предусловия**:

1. Подключиться к сайту с двух аккаунтов.

2. С первого аккаунта создать игру в Checkers.

3. Со второго аккаунта подключиться к игре через кнопку JOIN.

4. Апрувнуть все.

**Шаги воспроизведения**:

1. Кликнуть по кнопке "Checkers rules notice" вне текста

**Ожидаемый результат**:

Кнопка кликается 

**Фактический результат**:

Кнопка кликается исключительно при клике на текст

**Comment by anastasiabusygina** [comment]
В результате вся кнопка должна стать кликабельной, включая текст и значок внутри кнопки.
Включает в себя задачу #119

**Comment by originalskobka** [comment]
Кнопка кликается в любом месте. 



![Image](https://user-images.githubusercontent.com/121563260/214903639-eae65358-185d-4fac-88ad-43a07b92c2a5.jpg)
![Image](https://user-images.githubusercontent.com/121563260/214903641-85913e54-2bb8-4020-8bc3-106842c645f9.jpg)
![Image](https://user-images.githubusercontent.com/121563260/214903640-2160e75c-366c-4dd1-9648-34e4a47f850a.jpg)
