### ISSUE TITLE
Элемент (Круг с восклицательным знаком) в кнопке "Checkers rules notice"  не нажимается

### ISSUE THREAD

**Issue by originalskobka** [chainhackers/gamejutsu-demos#119]
**Предусловия**:

1. Подключить кошелек

2. Создать игру в Checkers

**Шаги воспроизведения**:

1. Кликнуть по элементы внутри кнопки "Checkers rules notice"

![Image](https://user-images.githubusercontent.com/121563260/213919684-ee4e1d9c-3bd6-4f5e-a412-799558253104.JPG)

**Ожидаемый результат**:

Элемент кликается 

**Фактический результат**:

Элемент не нажимается

**Comment by anastasiabusygina** [comment]
@utgarda @poludnev @originalskobka Забираю задачу на доработку дизайна, раз элемент дизайна вызывает вопросы

**Comment by anastasiabusygina** [comment]
Задача входит в состав задачи #118.
Закрываю.
