### ISSUE TITLE
Delete 'isJump' field

### ISSUE THREAD

**Issue by pixelPepe** [chainhackers/gamejutsu-demos#144]
https://github.com/chainhackers/gamejutsu-contracts/issues/26

- [x] найти места в коде, в которых формируется ход и приводятся типы ходов
- [x] спросить у @poludnev где берется abi в polygonScan или файликом при билде, уточнить правильность предыдущего пункта
- [x] drop `isJump` field from move structure
- [x] test move packing
- [x] make sure GithubActions build and tests still pass

**Comment by utgarda** [comment]
https://github.com/ethers-io/ethers.js/discussions/3095
