### ISSUE TITLE
Новые игры не отображаются в Join a game

### ISSUE THREAD

**Issue by originalskobka** [chainhackers/gamejutsu-demos#147]
**Шаги воспроизведения**:
1. Создать игру
2. Со второго устройства зайти в Join a game

**Ожидаемый результат**:
После создания игры, новая игра отображается в Join a game

**Фактический результат**: 
После создания игры, игра в join a game не отображается.

В Крестиках-Ноликах находится 1 запись с 0 айди.

![Image](https://user-images.githubusercontent.com/121563260/222690839-a6e0383e-3bef-4e0d-9a66-05e8cba1f9f5.png)

В шашках никаких записей нет

![Image](https://user-images.githubusercontent.com/121563260/222690781-83ba617f-e22c-46e8-abd1-4c7e2de12e63.png)

**Comment by anastasiabusygina** [comment]
@originalskobka Добавляй пожалуйста в описание указание Prod или Dev

**Comment by anastasiabusygina** [comment]
@originalskobka Отправь сссылку на транзакцию создания игры, пожалуйста

**Comment by originalskobka** [comment]
@anastasiabusygina 
Скорее всего проблема была на моей стороне, хотя кеш чистил :\

Сейчас все ок, думаю можно закрыть.

https://polygonscan.com/tx/0xaf7232f6c3647683fed359b562f6b855df4ca3f04a22bda6a53a9081d7c15f71

**Comment by anastasiabusygina** [comment]
Закрывай задачу) @originalskobka

**Comment by originalskobka** [comment]
Мой косяк, задачу закрыл
