### ISSUE TITLE
Game selection page / Pick Page Mobile Layout 

### ISSUE THREAD

**Issue by anastasiabusygina** [chainhackers/gamejutsu-demos#158]
- [x] create a main game selection page. task are done when the marked part of the page is ready

![Image](https://user-images.githubusercontent.com/89840876/233832749-abc8a619-176c-4e2a-8b33-c4a411b40e50.png)

- [x] create a state component that determines which page we are on - gamedemo or mygames
- [x] create a component that displays games on the gameDemo tab
- [x] show the address of rules contract
- [x] make the button startGame send a transaction
- [x] show the icons of games
- [x] make drop menu from button start new game
- [x] make a description of game
- [x] make a button to start new game without stake
- [x] make a button to start new game with stake
- [x] make a preloader for state when transaction still not confirmed
- [x] make the button joinGame redirect to old joinGame page
- [x] create a component that displays games on the myGames tab
- [x] if the user is not authorized, redirect him to the authorization page

![Image](https://user-images.githubusercontent.com/89840876/230288551-0e38df05-520b-484f-80eb-8dd8dadb48a4.png)

ctive tab - black, inactive tab - gray
![image](https://user-images.githubusercontent.com/89840876/233833000-ca308ab2-6d25-4677-8276-96d436afc83b.png)

**Comment by anastasiabusygina** [comment]
- [ ] active tab - black, inactive tab - gray

![Image](https://user-images.githubusercontent.com/89840876/233832749-abc8a619-176c-4e2a-8b33-c4a411b40e50.png)

**Comment by originalskobka** [comment]
Пишу комментарий при Dev 1.2.4

1. По скринам из задачи у нас 2 кнопки: Game Demo и My Games - фактически имеем 3 кнопки: Game Demo l Join game l  My Games


![Image](https://github.com/chainhackers/gamejutsu-demos/assets/121563260/e17db0c5-ebe0-45eb-8291-3389c3d9e219)

2. Кнопка Join (в выборе для игры) отправляет на Список общий список игр, где отображаются Checkers и Tic-Tac-Toe. Не имеет значения на какую кнопку Join мы нажмем, в начале списка всегда будут игры Checkers 

(Клик на Join просто переводит в Join game (лишняя кнопка, описанная в первом пункте), где содержится общий список мачей для двух игр.)

3. Проверить отображения в MyGames истории игр не могу, тк истории нет, а игру сыграть не могу. Игра создается, к ней можно законнектиться со второго акка. Но игроки не видят друг друга, в консоли ошибка post 403.  Спам в консоли прикрепил в логах.

[123.log](https://github.com/chainhackers/gamejutsu-demos/files/11553038/123.log)

________________________________________________________________

Находясь в Game Demo в хлебных крошках доступно к клику Game Demo, если кликнуть на нее то получаем такой результат.  В целом находясь в Game Demo у нас не может быть возможность "активного" клика по Game Demo в хлебных крошках

При клике по V2, аналогичная ситуация с отображением страницы 



![Image](https://github.com/chainhackers/gamejutsu-demos/assets/121563260/32a42422-6234-4513-8ca7-b84476a75cab)
