### ISSUE TITLE
Join a game page layout

### ISSUE THREAD

**Issue by anastasiabusygina** [chainhackers/gamejutsu-demos#159]
- [x] #175
- [x] create a component that displays a list of games
- [x] create a component inside the previous component that reflects the list of existing **started** games
- [x] display the **started** game ID inside the last component
- [x] display whether the **started** game has a bet
- [x] display the **started** game creator's wallet with a pseudographic
- [x] create a Join button that allows you to join the **started** game
- [x] display the game icon
- [x]  the address of the game contract with a pseudographic

![Image](https://user-images.githubusercontent.com/89840876/233833165-38bc9fe5-3d77-4760-9a06-e54d9991e47e.png)

**Comment by originalskobka** [comment]
Игра со ставкой отображается, но при создании игры не списывается ставка. (берется только комса за создание игры) 

Вот тхн линк - https://polygonscan.com/tx/0xa43cc4d4373ba01c0ada7074e0dc2c01a4feafc4edd9d90f573438e3b9068b35 

И собственно мой адрес, если нужен - 0x7ae530a65890adc1708D6A259F6E706e2AF1f297

**Comment by anastasiabusygina** [comment]
@originalskobka Эта задача на верстку, поэтому списание ставки не относится к этой задаче. В таком случае следует завести отдельный баг, не привязанный к задаче по верстке. Тут проверь пожалуйста, что все ссылки ведут туда, куда должны.

**Comment by originalskobka** [comment]
Vse ok
