### ISSUE TITLE
Team Page Mobile Layout

### ISSUE THREAD

**Issue by anastasiabusygina** [chainhackers/gamejutsu-demos#165]
- [x] heading "meet our team"
- [x] subtitle "Enthusiasts of making products better"
- [x] team member cards
> - [x] Display a photo
> - [x] Display name
> - [x] Display a role in a team
> - [x] Display a block with information about the participant
> - [x] Display links to social networks of participants
- [x] heading "You have an idea? We have the talents!"
- [x] contuct us button

![Image](https://user-images.githubusercontent.com/89840876/234244216-22c18e41-fb9a-4ed7-adef-e6377dff11fa.png)

**Comment by pixelPepe** [comment]
-[ ] fix join game button in JoinGame component 
-[ ] display list of my games in MyGames component

**Comment by originalskobka** [comment]
- [ ] heading "meet our team"
- [ ]  subtitle "Enthusiasts of making products better"
- [ ] heading "You have an idea? We have the talents!"
- [ ]  team member cards
> - [ ] Display a photo
> - [ ]  Display name
> - [ ]  Display a role in a team
> - [ ]  Display a block with information about the participant
> - [ ]  Display links to social networks of participants
- [ ] contact us button

**Comment by anastasiabusygina** [comment]
Contact us оставить нерабочей кнопкой.

Заметила, что есть элемент, который не влезает в ширину экрана

![Image](https://github.com/chainhackers/gamejutsu-demos/assets/89840876/fa29b6c0-cc29-462d-97e1-9f2193b7b704)
