### ISSUE TITLE
Player who lose is not got informed that the game is finished and the player loses the game. #tictactoe

### ISSUE THREAD

**Issue by anastasiabusygina** [chainhackers/gamejutsu-demos#52]
+ and does not informed that is disqualified

**Comment by originalskobka** [comment]
Уведомление о дисквалификации имеется.


![Image](https://user-images.githubusercontent.com/121563260/212066359-f0fad313-c204-4e2d-884e-929866223882.JPG)


Уведомление о победе оппонента есть.


![Image](https://user-images.githubusercontent.com/121563260/212066370-25e0e5c4-6484-4a68-b871-b785472f353f.JPG)

**Comment by anastasiabusygina** [comment]
@originalskobka это на дев или на проде тоже есть?
Все что есть на проде внесу в задачу #93
