### ISSUE TITLE
После каждого хода второго игрока включается disputemove #checkers

### ISSUE THREAD

**Issue by anastasiabusygina** [chainhackers/gamejutsu-demos#56]
- если нажать dispute move по окончании игры, то ошибка:

![Image](https://user-images.githubusercontent.com/89840876/202864926-49b3b5a5-2c7d-4990-ab33-051a1a92064e.png)

**Comment by utgarda** [comment]
can't reproduce. @anastasiabusygina please try running new versions with a script like
```shell
BRANCH=front-01
git clone git@github.com:chainhackers/gamejutsu-demos.git
cd gamejutsu-demos
yarn install
yarn dev
```
