### ISSUE TITLE
Adaptive layout

### ISSUE THREAD

**Issue by anastasiabusygina** [chainhackers/gamejutsu-demos#64]
Адаптивная верстка для мобильных устройств.
Файл дизайна отсуствует. 
Перевестать страницы  для мобильных устройств таким образом, чтобы все элементы помещались на экране.

- [x] Main Page
- [x] Choose a game demo
- [x] Let’s get you started
- [x] How would you like to begin?
- [x] Winner gets \ Start Game
- [x] Join a Game
- [x] Tic-Tac-Toe Game
- [x] Checkers Game
- [x] Meet The Team

**Comment by originalskobka** [comment]
**1. Ошибка поверх кнопки** 


![Image](https://user-images.githubusercontent.com/121563260/211328801-23741e81-bf04-4c06-84a3-6672d2cc3742.png)


**2. Текст в кнопке при создании игры** 


![Image](https://user-images.githubusercontent.com/121563260/211328879-53a6d650-8848-43a2-bd26-1178843ffa96.png)

**3. Выравнивание текста в случае победы/поражения** 


![Image](https://user-images.githubusercontent.com/121563260/211329067-98aa5792-017a-40e3-95c1-ad4d00cd9788.png)



![Image](https://user-images.githubusercontent.com/121563260/211329090-7ca2a42d-247a-4b77-87f3-0c6c4453e687.png)


**4. После завершения игры отображаются только 4 последних хода, посмотреть остальные не удается, нет возможности заскролить данную панель** 


![Image](https://user-images.githubusercontent.com/121563260/211329261-4689d122-9a6b-46f1-baca-98f9d9eba4d4.png)

**Comment by anastasiabusygina** [comment]
@originalskobka спасибо, давай теперь класть задачи, требующие доработки, обратно в колонку In Progress

**Comment by originalskobka** [comment]
1. После завершения игры отображаются только 4 последних хода, посмотреть остальные не удается, нет возможности заскролить данную панель

![Image](https://user-images.githubusercontent.com/121563260/211564133-98b030ff-662a-49f9-978a-3403a6b3660f.png)



2. Выравнивание текста в случае победы/поражения



![Image](https://user-images.githubusercontent.com/121563260/211564173-dc618b01-685b-4041-90b0-e5b1f18b45e9.png)

**Comment by anastasiabusygina** [comment]
@ghUserrrr в этой задаче осталось только выравнивание значков. Что-то требуется тебе, чтобы доделать это выравнивание? 
Предыдущий комментарий, пункт 1, "После завершения игры отображаются только 4 последних хода, посмотреть остальные не удается, нет возможности заскролить данную панель" , имеются ввиду 4 последних значка.

**Comment by anastasiabusygina** [comment]
@ghUserrrr 
поправить выползающие кнопки


![Image](https://user-images.githubusercontent.com/89840876/211812472-091d378b-87a3-4837-899c-42ac696a88fe.png)

**Comment by ghUserrrr** [comment]
исправил верстку со скринов выше, отправил коммиты @poludnev

**Comment by anastasiabusygina** [comment]
С компа нормально заходит в игру, с мобилки не получается ни сделать игру, ни подключиться, из-за кошелька. Он или не грузится, или не возращется из кошелька обратно в игру.
https://t.me/c/1706516893/400

**Comment by originalskobka** [comment]
Кнопки отображаются, как и раньше. При клике выползают за рамки.
Значки до сих пор нельзя скролить. (См. мой последний комментарий под № 1)

**Comment by originalskobka** [comment]
Значки отображаются корректно.
При клике по кнопкам, они не выползают за рамки.
