### ISSUE TITLE
UI improvements - reduce clicks per move 

### ISSUE THREAD

**Issue by utgarda** [chainhackers/gamejutsu-demos#67]
![ui](https://user-images.githubusercontent.com/15115/209654299-9ad7973f-04df-4cfb-9480-fd00c67ff29b.jpg)

The current checkers UI is supposed to allow all kinds of moves, including illegal ones, to the player, which results in forcing the player to make a lot of choices during every move. On-chain game rules represent multi-hop jumps as multiple moves where all the moves but the last one change the game state in such a way, that after a non-final jump it's still the same player's turn. So each hop of a multi-jump move produces a separate game state which is signed and sent to the opponent, and that adds another degree of freedom to the user, so there's a separate button to indicate if the jump is the final one.

2 buttons for a simple move - "cancel" and "really, make this move"
![simple_move_buttons](https://user-images.githubusercontent.com/15115/209656124-80a5fe43-7f14-4290-90e6-9f2bc69c7f95.jpg)

3 buttons for a jump - "cancel", "make the final move, pass the turn to the opponent", and "make the jump, keep the turn and make another jump after this one"
![3_buttons_after_jump](https://user-images.githubusercontent.com/15115/209656379-866dac5b-b43f-455e-87f5-559833a6cdbb.jpg)

this UI served us well for testing the system, and turned out too hard to explain to anyone else who want to try a GameJutsu demo and actually play a game of checkers. It requires quite a lot of concentration to just click the right buttons to make legal moves intended by a player.

This UI can be greatly improved by 

* allowing only the legal moves, same as every usual online checkers page - check an example below
* adding an explicit way for the user to making an illegal move, something that does not demand extra attention when the user is OK with just playing the game ( like a "cheat" button )

A [user-friendly UI example](https://www.247checkers.com/)
![checkers247](https://user-images.githubusercontent.com/15115/209657569-98b09252-001b-44d2-bc9b-af3586315330.png)

In case a user decides to cheat, these values should be editable, and optionally shown on the board:
* `from` - the number of cell originating the move
* `to` - the number of cell where the player checker should land
* `isJump` - the boolean flag saying if the move is a jump
* `passTurn` - the boolean flag saying if the opponent should move next

**Comment by anastasiabusygina** [comment]
https://www.figma.com/file/Yb10NEuE6IVRPvGVEL8qLZ/%F0%9F%8E%B2-GameJutsu_design?node-id=0%3A1&t=Ov1g0i02RrwV449Y-1
