### ISSUE TITLE
Крестики-нолики, ничья: нет отображения финального экрана

### ISSUE THREAD

**Issue by anastasiabusygina** [chainhackers/gamejutsu-demos#68]
![Image](https://user-images.githubusercontent.com/89840876/209658903-2bda193e-8832-4276-841e-2dbd0a9693aa.png)

**Comment by anastasiabusygina** [comment]
Сценарии для игроков 1 и 2 после того, как доска заполнена и находится в состоянии "ничья":

Для игрока 1:
- показана кнопка Claim Win (нажимает)
- показан экран Wait + одновременно вызывается Metamask
- после подтверждения транзакции в Metamask показан экран со значками

Для ирока 2:
- показана кнопка Claim Win
- (показан экран, показывающий, что оппонент уже нажал claim win и вызвал транзакцию)
- после подтверждения оппонентом транзакции в Metamask показан экран со значками

**Comment by originalskobka** [comment]
Когда доска заполнена и находится в состоянии "ничья":

Игрок 1 (создатель игры) и Игрок 2 видят текст - "It seem's to be a draw" и кнопку "confirm draw"
 
Игрок 1 (создатель игры) нажимает кнопку - "confirm draw", подтверждает транзакцию и видит экран со значками. 

Игрок 2 продолжает видеть "It seem's to be a draw" и кнопку "confirm draw". При попытке нажать кнопку получает [ошибку](https://disk.yandex.ru/d/YLbcxt3PIByp7A). 

У игрока 2 не работает кнопка в любой момент (до нажатия кнопки "confirm draw" создателем игры и после).

**Comment by originalskobka** [comment]
Ничего не изменилось, вернул на доработку

**Comment by anastasiabusygina** [comment]
@ghUserrrr Забыл доложить скриншоты до/после

**Comment by ghUserrrr** [comment]
now both players can end the games in a draw
![firefox_EYQyOaO9Ta](https://user-images.githubusercontent.com/109285732/222685821-708ed91d-421d-4dbf-ab29-57ca6cf681aa.png)

**Comment by originalskobka** [comment]
Не могу проверить, см #147

**Comment by originalskobka** [comment]
Все ок, транзакцию на завершение игры можно вызвать у любого из игроков. 

Игра завершается у обоих



![Image](https://user-images.githubusercontent.com/121563260/222737819-cf3fef87-524d-42e1-9d1d-e31a9826bf6c.png)
