### ISSUE TITLE
Реализовать корректное окончание игры при неправильном последнем ходе

### ISSUE THREAD

**Issue by anastasiabusygina** [chainhackers/gamejutsu-demos#69]
Когда последний сделанный ход не соотвествует правилам игры, должна быть возможность оспорить ход или не оспаривать его.
https://www.figma.com/file/K2Wv3dTRwbPYVrqDsDQkrI/ETH-Online-2022-(Copy)?node-id=0%3A1&t=s5x5iUyvF5048Uwt-1

![Image](https://user-images.githubusercontent.com/89840876/209665292-e5a640ee-2321-4ff8-8e8f-8e3225dbefa8.png)

**Comment by anastasiabusygina** [comment]
Сценарии для игроков 1 и 2 после того, как 1 сделал неправильный и при этом выигрышный ход. Игрок 1 завершает игру.

Игрок 1:
- видит кнопки Dispute Move и Claim Win
- нажимает claim win
- видит экран ожидания + открывается MetaMask
- подтверждает транзакцию 1
- видит сообщение с отказом от арбитра
- нажимает dipsute move
- видит экран ожидания + открывается MetaMask
- подтверждает транзакцию 2
- экран проигравшего

Игрок 2:
- видит  кнопку Dispute Move и заблокированный экран без кнопок
- после подтверждения транзакции 2 оппонентом видит экран победителя


Другой сценарий, где 1 также сделал неправильный и при этом выигрышный ход. Игрок 2 завершает игру.

Игрок 1:
- видит кнопки Dispute Move и Claim Win
- после подтверждения оппонентом транзакции видит экран проигравшего

Игрок 2:
- видит  кнопку Dispute Move и заблокированный экран без кнопок
- нажимает Dispute Move
- видит экран ожидания + открывается MetaMask
- подтверждает транзакцию
- видит экран победителя

**Comment by originalskobka** [comment]
@anastasiabusygina 

Есть несоответствие сценарию. Но в целом как бы работает. Закрывать или отправлять на доработку?  

По сценарию:
1. Читер видит диспут мув и финиш гейм.
2. Игрок 2 видит диспут мув и финиш гейм.
3. Читер может нажимать кнопки.


Фактически:
Диспут мув и финиш гейм видит только игрок 2, читер видит только диспут мув.

Какую-либо кнопку может нажать только игрок2. У читера нажатие на диспут мув - ошибка. 

Если игрок2 нажимает диспут мув или финиш гейм, то сценарий продолжается. Читер видит сообщение о проигрыше, тк дисквал. Игрок 2 видит сообщение о победе



![Image](https://user-images.githubusercontent.com/121563260/220071672-4091b856-e7f0-4b7c-8b99-a78d6e7c19fe.png)

**Comment by utgarda** [comment]
Пока нет возможности оспорить какой-то конкретный ход, в случае неправильного последнего хода обе кнопки - "Dispute move" и "Finish game" означают одно и то же. Поэтому не стоит их различать и показывать игрокам разные наборы. Принято, когда существует единственное доступное действие, предоставлять всем потенциально желающим его вызвать. Помните - это не игровой сервис, люди смотрят на работу протокола, а не играют в шашки по-настоящему. Нет причин скрывать от проигравшего возможность послать транзакцию - он же не по-настоящему проиграл.

**Comment by ghUserrrr** [comment]
now the cheater sees the "end the game" button
both players can end the game
cheater's screen: 

![Image](https://user-images.githubusercontent.com/109285732/222897203-97d34801-b7c6-411e-ae2f-6e2ee4423334.png)



![Image](https://user-images.githubusercontent.com/109285732/222897204-16c5e427-88b3-4f8f-ae63-db8afc22a1c0.png)

**Comment by originalskobka** [comment]
Все ок, транзу может вызвать любой игрок. Читер получает дисквал
