### ISSUE TITLE
Включить на страницу "шашек" объясняющий текст

### ISSUE THREAD

**Issue by anastasiabusygina** [chainhackers/gamejutsu-demos#91]
`This protocol demo shows the Arbiter using Checkers rules https://www.officialgamerules.org/checkers to judge if the game is played fair and square. The twist here is that a single move contains only one checker position change, i.e. when a player jumps multiple times, that is recorded as a sequence of separate moves, each containing one jump and a flag indicating who's to move next. This may not be the smoothest UX, it is done to demonstrate ways of encoding game rules on-chain that don't require complicated programming.`

**Comment by anastasiabusygina** [comment]
Окно есть только в мобильной версии, вернула задачу в InProgress - доделать web-версию.

**Comment by poludnev** [comment]
@ghUserrrr suggest you go ahead with this task.

A red rectangle in the screenshot can be a place for the disclaimer.

You may have to revise the layout for the whole component. Now it is the flex, it may be better to change it to the grid, as the disclaimer element is shown only for the checkers.   

![Image](https://user-images.githubusercontent.com/51874367/212767465-1439abf4-511a-4abf-ba4f-ed5be0173275.png)

**Comment by ghUserrrr** [comment]
added disclaimer for desktop screen resolution
![Image](https://user-images.githubusercontent.com/109285732/212881908-c7b5a23a-b05f-43e4-b6e0-1cf08937bab0.png)
![Image](https://user-images.githubusercontent.com/109285732/212881907-4eb1fff6-b8ef-42b7-bb6e-7c2bd4ae6290.png)
![Image](https://user-images.githubusercontent.com/109285732/212881906-cc9425bf-9d4d-47ec-a228-85be37ef7d37.png)

**Comment by originalskobka** [comment]
Объясняющий текст имеется в мобилке и web.
