### ISSUE TITLE
В Checkers в мобильной версии некорректно отображается окно "Issues your ZK Badge"

### ISSUE THREAD

**Issue by originalskobka** [chainhackers/gamejutsu-demos#99]
**Шаги воспроизведения**:
1. Завершить партию
2. Заклеймить награду у победителя

**Ожидаемый результат**:
Окно "Issues your ZK Badge" отображается корректно: видно все значки, окно "Issues your ZK Badge" полностью помещается.

**Фактический результат**: 
Окно "Issues your ZK Badge" отображается некорректно: окно "Issues your ZK Badge" отображается частично.

![Image](https://user-images.githubusercontent.com/121563260/212064451-48b5ffcb-b5b7-4d24-a0a9-c5e9d9693d36.png)

**Comment by ghUserrrr** [comment]
fixed
![Image](https://user-images.githubusercontent.com/109285732/215521360-d2ffa4e9-00fd-4b71-b859-ac4bb674d899.png)

**Comment by originalskobka** [comment]
Проверить задачу не могу. См. #138

**Comment by anastasiabusygina** [comment]
@ghUserrrr Здесь тоже не понятно, что изменилось. Последние комментариии говорят о том, что задачу проверить невозможно.

**Comment by ghUserrrr** [comment]
bug with move 9 fixed
![chrome_g4WskkqOU4](https://user-images.githubusercontent.com/109285732/222684934-1d305f45-e002-4f85-bc4f-2b54c0bb061c.png)
![chrome_hJUxEkOFom](https://user-images.githubusercontent.com/109285732/222684939-3057e393-534d-414e-bc65-af203ea4f120.png)
![chrome_57dduBVI9b](https://user-images.githubusercontent.com/109285732/222684943-1ceb4320-8d82-4ba4-834c-dc53bae6c2ad.png)

**Comment by originalskobka** [comment]
Не могу проверить, см #147

**Comment by originalskobka** [comment]
@ghUserrrr Ничего не поменялось) 


![Image](https://user-images.githubusercontent.com/121563260/222940316-885a7859-fbd7-4a08-957f-1ebc467e5426.png)



Кеш чистил. Тыкал с чистого браузера. Ничего не поменялось

Думаю, это связано с тем, что я прописал в задаче Checkers + приложил скрин именно с шашек. Ибо проблема наблюдалась только в шашках. 

А судя по твоим скринам, ты проверяешь в крестиках-ноликах, в которых проблема не наблюдалась.

Но тк у меня какие-то проблемы возникают в последнее время, давай позовем @anastasiabusygina.

@anastasiabusygina, не могла бы ты протыкать шашки и посмотреть, проблема сохранилась или наблюдается только у меня? 


И сразу второй вопрос. Если проблема сохранилась,  есть ли смысл продолжать гонять в этой задаче @ghUserrrr по визуалу, если скоро будет новый?

**Comment by ghUserrrr** [comment]
fixed badges in checkers

![Image](https://user-images.githubusercontent.com/109285732/222948411-978ceca9-b92e-45b7-a6a3-10637170350f.png)

**Comment by originalskobka** [comment]
Все ок.


![Image](https://user-images.githubusercontent.com/121563260/224493836-bd767a62-52bd-493f-b0e4-7abf7bacdca3.png)
